remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: Documentación

nombres: Juan David Zapata Márquez
submodulo: Programación para la web
periodo: 2023-2
url_foto: https://firebasestorage.googleapis.com/v0/b/datbase1-96066.appspot.com/o/fotopersonal%20(1).jpg?alt=media&token=592b9585-67f5-49a9-8ebd-ca567e4e1da1&_gl=1*bn9faw*_ga*MTk0NTQwNzUxNi4xNjc5MTQ0MDk3*_ga_CW55HF8NVT*MTY5NjA4NTE4MC42LjEuMTY5NjA4NTUyNi4yMy4wLjA.

